new auth/profile/wallet logic WIP [bugs]
Astraly-Labs/astraly-frontend pull request #32
Opened 2022-10-11 09:31 UTC by jjjuk

2022-10-17 12:04 UTC, EvolveArt requested changes

2022-10-17 12:04 UTC, EvolveArt commented on src/layout/index.tsx
> +          // TODO: server to client wallet connection logic
more details on that please

2022-10-17 12:20 UTC, jjjuk commented on src/components/Pages/Auth/PassReset.tsx
> +  const submit = () => {}
fixed

2022-10-17 12:21 UTC, EvolveArt reviewed
Do we check that the user doesn't change to the same password than before ?

2022-10-17 13:42 UTC, jjjuk commented
> Do we check that the user doesn't change to the same password than before ?
No, we don't

2022-10-18 09:06 UTC, EvolveArt commented on next.config.js
> +      'https://8ce1-146-255-233-146.eu.ngrok.io/api' /* 'https://zkpad-api.herokuapp.com/api' */,
wrong url here ?

2022-10-18 19:07 UTC, jjjuk commented on src/components/Pages/Auth/AuthForm.tsx
> +      <div className="mb-28px">
We haven't had any of these in the app, so... I prefer just use immer for forms. It's not even a "package" its just an immutability wrapper. Don't see it more difficult to work with, prefer not to grow packages size and have more control over process)

2022-10-18 19:14 UTC, jjjuk commented on src/components/Pages/Auth/AuthForm.tsx
> +      <div className="mb-28px">
About 
```html 
<form>...</form>
``` 
it's a good point 🤣

2022-10-18 19:17 UTC, jjjuk commented on src/hooks/useEagerConnect.js
> +    if (!_connector) return // 🫶
Don't need to continue execution if there is no _connector)

2022-10-18 19:25 UTC, jjjuk commented on src/layout/index.tsx
> +          // TODO: server to client wallet connection logic
We discussed that in some scenario we need to connect wallet from data fetched from the server, so having just an address, but not from useStarknetReact() and extensions. You said that it's your job. So this comment tells the place where this logic should start. If it's inconvenient to you, feel free to suggest your options!

2022-10-19 08:23 UTC, merged